.travis.yml, Gopkg.lock, clients_influx.go, clients_type.go, parsers.go, uap_influx.go, uap_type.go, unifi.go, unifi_test.go, usg_influx.go, usg_type.go, usw_influx.go, usw_type.go
Adds each site's name to the tags on the metrics in each measurement.
Also implements code testing and lint using travis ci.
=> Add site name to all assets. Include Travis build.

.travis.yml, README.md, clients_influx.go, clients_type.go, parsers.go, site_influx.go, site_type.go, types.go, unifi.go
This contribution adds better support for grabbing `Site` metrics. Also adds a comment to get the controller version.
=> Provide Site metrics

unifi.go
Adds a method to easily get the raw data from any path.
=> Add GetJSON method.

clients_influx.go, clients_type.go
This contribution brings the client data struct up to date. I found a few new pieces of information, and added them. Reorganized some of the other data too. Found a bug with duplicate client names, so switched to using Mac address; better.
=> Update client data.

networks.go
noticed this when i rebased, sorry
=> Fix argument bug in networks.go

go.mod, go.sum, unifi.go, unifi_test.go
I've been able to use this great library to make actual changes to devices by making these alterations.
Should all be backwards compatible and I also added small unit test in line with existing.
My use case  - I wanted to programmatically control the LED on my UAP. Happy to share that code too in a separate PR.
Thanks for considering!
=> Support PUT calls for REST API

.travis.yml, alarms.go, anomalies.go, devices.go, dpi.go, events.go, go.mod, go.sum, ids.go, networks.go, site.go, types.go, udm.go, unifi.go, unifi_test.go, usg.go, usw.go, uxg.go
- This contribution adds support for UXG devices. (for https://github.com/unifi-poller/unifi-poller/issues/296)
- Also adds missing Storage struct to UDM devices to close #42.
- Adds USG temperatures. (for https://github.com/unifi-poller/unifi-poller/issues/269)
- Exposes the http timeout.
- Exposes all the custom errors.
- Fixes lint, updates modules, wraps all returned errors.
=> Add UXG data struct, storage for UDM, and other minor improvements.

.travis.yml, alarms.go, anomalies.go, clients.go, devices.go, events.go, go.mod, go.sum, ids.go, site.go, uap.go
A bug was introduced that sets site name incorrectly on all devices. This contributions should fix that. 
Problem reported in https://github.com/unifi-poller/unifi-poller/issues/341.
I also fixed up a few other places that concatenated site name when it was already available.
=> site name is wrong, fix it.

users.go
mirrors #57 so we can merge this
=> User updates 

clients.go
more int64 to FlexInt fixes
https://github.com/unpoller/unpoller/issues/575 
We will just change them all 🙃 thanks ubiquiti
=> fixes more int64 -> flexint

mocks/mock_server.go
need direct access for an integration test.
=> expose the mock server directly

mocks/mock_client.go, mocks/mock_server.go, types.go, unifi.go
Finishes mocking the server data response
=> Mock Server Data

mocks/mock_client.go, mocks/mock_server.go, types.go, unifi.go
Should be the last bits necessary to start plumbing in the server status. 🤞
=> plug in mock status response and improved logging

devices.go, mocks/mock_server.go, pdu.go, uap.go, udm.go, usg.go, usw.go, uxg.go
fixes the mock server response for the devices -- the format is slightly different than expected.
We also codify the expected types directly
=> Mocking Devices Fix

.github/workflows/build.yml, .github/workflows/release.yml, .golangci.yaml, .goreleaser.yaml, alarms.go, anomalies.go, clients.go, devices.go, devmgr.go, dpi.go, events.go, ids.go, mocks/mock_client.go, mocks/mock_server.go, networks.go, pdu.go, pdu_test.go, site.go, types.go, uap.go, udm.go, unifi.go, users.go, usg.go, usw.go, uxg.go
Adds linting to this repo as well and addresses lint report
Improves release process to mirror `unpoller/unpoller`
=> Apply Linting, Improve Release Process

alarms.go, anomalies.go, clients.go, devmgr.go, dpi.go, events.go, ids.go, mocks/mock_client.go, networks.go, pdu.go, site.go, types.go, uap.go, udm.go, users.go, usg.go, usw.go, uxg.go
- Linting
- Ordering of Fields in Structs for readability
- Fixes mock_client and mock_server to be more consistent in responses for unpoller integration tests.
=> updates lib for integration tests in unpoller + linting

alarms.go, events.go, examples/events.json
catname on other types also changed to an arraystring from user reports
=> More String/ArrayString changes to unifi responses

.github/workflows/build.yml, .gitignore, clients.go, ids.go, mocks/mock_client.go, mocks/mock_server.go, pdu.go, site.go, types.go, uap.go, unifi.go, usw.go, uxg.go
- Addresses lint failures
- Updates to golangci-lint 1.62
=> address linting issues

ubb.go, uci.go
part of support for https://github.com/unpoller/unpoller/issues/409 and https://github.com/unpoller/unpoller/issues/732
=> add ubb and uci from dumps

README.md, anomalies.go, devices.go, devmgr.go, events_test.go, mocks/mock_client.go, networks.go, pdu_test.go, types.go, types_test.go, ubb.go, uci.go
for https://github.com/unpoller/unpoller/issues/732 and https://github.com/unpoller/unpoller/issues/409
=> now add interface to retrieve and parse ubb and uci

types.go, unifi.go, unifi_test.go
=> add support for api-key auth
